id: P010568
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-20 10:14:29.979676
source_metadata:
  id: bdr:W1PD105852
  title: ཀུན་འདུས་མེ་ལོང་།
  author: ''
  volumes:
    6c8c9c428d5f406fa8e8322d0b27d9de:
      image_group_id: I1PD105854
      title: ''
      volume_number: 1
      total_pages: 242
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
